### ISSUE TITLE
use `jstransformer`

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/readme-generator#1]
we can use awesome [jstransformer](https://github.com/jstransformers/jstransformer) - normalizes the API between any template engine or `css processor` - any js transformation, we have 70+ transformers with normalized api.

**Comment by jonschlinkert** [comment]
what!??!? lol that's what template and verb are for!

**Comment by jonschlinkert** [comment]
also, fwiw it's just following consolidate conventions. we already support those conventions everywhere.

**Comment by tunnckoCore** [comment]
@jonschlinkert `template` do a lot more things than `jstransformer` do - normalizing only the `.render` and `.compile` methods and passing options to them.

**Comment by jonschlinkert** [comment]
sorry, I can't see the need for it.
