### ISSUE TITLE
npm package missing templates

### ISSUE THREAD

**Issue by tomByrer** [jonschlinkert/readme-generator#2]
`Error: ENOENT: no such file or directory, open 'C:\Users\tom\AppData\Roaming\npm\node_modules\readme-generator\\template.md'`
`Error: ENOENT: no such file or directory, open 'C:\Users\t\AppData\Roaming\npm\node_modules\readme-generator\templates\footer.md'`

Yep, not in there.  After I manually copied the files I got `√ successfully generated README.md`

**Comment by doowb** [comment]
Fixed via #4
