### ISSUE TITLE
If name, bugs, etc are missing from package.json it fails

### ISSUE THREAD

**Issue by vjpr** [jonschlinkert/readme-generator#5]
```
> readme
engine.templateSources[1]:19
((__t = ( bugs.url )) == null ? '' : __t) +
          ^

ReferenceError: bugs is not defined
```

**Comment by jonschlinkert** [comment]
pr?

**Comment by Primajin** [comment]
I'm not sure how to implement such a feature to open a PR. But it would be great if it allows you to type in something via the command line, when a property is not found.

**Comment by jonschlinkert** [comment]
see the [data section](https://github.com/jonschlinkert/readme-generator#data) of the readme. I also added the `expand-pkg` library, which "expands" package.json into an object that is ideal for rendering templates.

**Comment by Primajin** [comment]
umm I'm not quite sure if your readme is correct / fool-proof..
first:
> `$ npm i -g <%= name %>`
should be `$ npm i -g readme-generator` right?

and second:
> Given the template Name: <%= foo %>, the following:
> `$ readme --foo bar`
> Would render `Name: bar`

Wouldn't it be `$readme --name bar`? ;)

**Comment by doowb** [comment]
> should be $ npm i -g readme-generator right?

Yes, this was a typo in the `.readme.md` template where `<%%= name %>` should have been `<%= name %>`. `readme-generator` is being used to generate it's own readme! I fixed that typo and pushed up the new README.md

> Wouldn't it be $readme --name bar?

No, the example is showing that you can use a custom variable specified on the command line inside your template. The template is using `foo` in `<%= foo %>`, so you can specify a value for `foo` on the command line by typing `--foo bar` where `bar` is the value for `foo`.
